sudo: false
dist: xenial
language: generic
services:
  - docker
cache: ccache
env:
  global:
    - ROS_DISTRO=kinetic
  matrix:
    - DOCKER_IMAGE=flickfit/ubuntu-16-pcl-1.8.1:latest
before_install:
  - export CI_SOURCE_PATH=$(pwd)
  - export ROSINSTALL_FILE=$CI_SOURCE_PATH/dependencies.rosinstall
  - CATKIN_OPTIONS=$CI_SOURCE_PATH/catkin.options
  - export REPOSITORY_NAME=${PWD##*/}
  - export ROS_PARALLEL_JOBS='-j8 -l6'
  - export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages
script:
  - docker run --rm -i -v $CI_SOURCE_PATH:$CI_SOURCE_PATH -v $HOME:$HOME -e "CI_SOURCE_PATH=$CI_SOURCE_PATH" -e "HOME=$HOME" -e "ROS_DISTRO=$ROS_DISTRO" -e "ROSINSTALL_FILE=$ROSINSTALL_FILE" -e "CATKIN_OPTIONS=$CATKIN_OPTIONS" -e "ROS_PARALLEL_JOBS=$ROS_PARALLEL_JOBS" -e "DOCKER_IMAGE=$DOCKER_IMAGE" -t $DOCKER_IMAGE sh -c "cd $CI_SOURCE_PATH; ./.travis.sh"